services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  ml-service:
    build:
      context: ..
      dockerfile: ml-service/Dockerfile
    env_file:
      - ../ml-service/.env.example
    ports:
      - "8001:8001"
    depends_on:
      - mongo

  server:
    build:
      context: ..
      dockerfile: server/Dockerfile
    env_file:
      - ../server/.env.example
    environment:
      MONGO_URI: mongodb://mongo:27017/medguard
      REDIS_URL: redis://redis:6379/0
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
      - minio
      - ml-service

volumes:
  mongo_data:
  minio_data:
